controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    maci_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    maci_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    use_sim_time: True

maci_joint_state_broadcaster:
  ros__parameters:
    use_sim_time: True

maci_controller:
  ros__parameters:
    joints:
      - ur5_shoulder_pan_joint
      - ur5_shoulder_lift_joint
      - ur5_elbow_joint
      - ur5_wrist_1_joint
      - ur5_wrist_2_joint
      - ur5_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - finger_joint
      - left_inner_finger_joint
      - right_outer_knuckle_joint
      - right_inner_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
